import { resolve, dirname, join } from 'path';
import { fileURLToPath } from 'url';
import fse from 'fs-extra';
import {
  NETWORKS,
  BASE_DEPS,
  BASE_DEV_DEPS,
  TEMPLATE_DEPS,
  type Template,
} from './constants.js';
import type { CliOptions } from './cli.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = resolve(__dirname, '..', 'templates');

function processTemplate(content: string, vars: Record<string, string>): string {
  return content.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] ?? `{{${key}}}`);
}

function buildPackageJson(options: CliOptions): string {
  const templateDeps = TEMPLATE_DEPS[options.template];

  const pkg = {
    name: options.projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev --turbopack',
      build: 'next build',
      start: 'next start',
      lint: 'tsc --noEmit',
      test: 'vitest run',
      'test:watch': 'vitest',
    },
    dependencies: {
      ...BASE_DEPS,
      ...templateDeps.deps,
    },
    devDependencies: {
      ...BASE_DEV_DEPS,
      ...(templateDeps.devDeps || {}),
    },
  };

  return JSON.stringify(pkg, null, 2);
}

function buildEnvExample(options: CliOptions): string {
  const net = NETWORKS[options.network];
  return `# ============================================================
# 0G Configuration — ${options.network}
# Generated by create-0g-app
# ============================================================

# ─── Master Switch ───────────────────────────────────────────
# Set to true once you've configured your keys below
ZERO_G_ENABLED=false

# ─── 0G Chain (EVM L1) ──────────────────────────────────────
# RPC endpoint for 0G Chain
ZERO_G_CHAIN_RPC_URL=${net.chainRpcUrl}
# Chain ID: ${net.chainId} (${options.network})
ZERO_G_CHAIN_ID=${net.chainId}
# Private key for signing transactions (0x-prefixed)
# Generate: node -e "console.log('0x'+require('crypto').randomBytes(32).toString('hex'))"
ZERO_G_CHAIN_PRIVATE_KEY=
# Block explorer
ZERO_G_CHAINSCAN_URL=${net.chainScanBaseUrl}

# ─── 0G Storage (Immutable Log + Mutable KV) ────────────────
# Storage indexer URL (use turbo for production)
ZERO_G_STORAGE_INDEXER_URL=${net.storageIndexUrl}
# Flow contract address on 0G Chain
ZERO_G_STORAGE_FLOW_ADDRESS=${net.storageFlowAddress}
# Storage explorer
ZERO_G_STORAGESCAN_URL=${net.storageScanBaseUrl}

# Optional: explicit KV RPC URL (auto-discovered if not set)
# ZERO_G_STORAGE_KV_RPC_URL=

# Stream ID for KV writes
# Generate: node -e "console.log('0x'+require('crypto').randomBytes(32).toString('hex'))"
# ZERO_G_STORAGE_STREAM_ID=

# 32-byte hex key for AES-256-GCM encryption (optional)
# Generate: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
# ZERO_G_STORAGE_ENCRYPTION_KEY=

# ─── 0G Compute (AI Inference) ──────────────────────────────
# Enable compute features
ZERO_G_COMPUTE_ENABLED=false
# Provider wallet address (from: 0g-compute-cli inference list-providers)
# ZERO_G_COMPUTE_PROVIDER=
# Provider endpoint (e.g., https://compute-network-18.integratenetwork.work)
# ZERO_G_COMPUTE_BASE_URL=
# API key (from: 0g-compute-cli inference get-secret --provider <ADDR>)
# ZERO_G_COMPUTE_API_KEY=
# Model name (e.g., qwen3.6-plus, zai-org/GLM-5-FP8, deepseek/deepseek-chat-v3-0324)
# ZERO_G_COMPUTE_MODEL=qwen3.6-plus

# Enable Sealed Inference (TEE-backed compute for privacy)
# ZERO_G_SEALED_INFERENCE_ENABLED=false

# ─── 0G Data Availability (Event Streaming) ─────────────────
# Requires a local 0g-da-client sidecar
ZERO_G_DA_ENABLED=false
# ZERO_G_DA_GRPC_URL=localhost:51001
# ZERO_G_DA_GRPC_TLS=false

# ─── App ─────────────────────────────────────────────────────
NEXT_PUBLIC_0G_NETWORK=${options.network}
`;
}

export async function scaffold(options: CliOptions, projectDir: string): Promise<void> {
  const vars: Record<string, string> = {
    PROJECT_NAME: options.projectName,
    NETWORK: options.network,
    CHAIN_ID: String(NETWORKS[options.network].chainId),
    RPC_URL: NETWORKS[options.network].chainRpcUrl,
    CHAINSCAN_URL: NETWORKS[options.network].chainScanBaseUrl,
    STORAGE_INDEX_URL: NETWORKS[options.network].storageIndexUrl,
    STORAGESCAN_URL: NETWORKS[options.network].storageScanBaseUrl,
  };

  // 1. Create project directory
  await fse.ensureDir(projectDir);

  // 2. Copy base template
  const baseDir = join(TEMPLATES_DIR, 'base');
  if (await fse.pathExists(baseDir)) {
    await fse.copy(baseDir, projectDir, { overwrite: true });
  }

  // 3. Copy template-specific files on top
  const templateDir = join(TEMPLATES_DIR, options.template);
  if (await fse.pathExists(templateDir)) {
    await fse.copy(templateDir, projectDir, { overwrite: true });
  }

  // 4. Process .tmpl files
  const allFiles = await listFiles(projectDir);
  for (const filePath of allFiles) {
    if (filePath.endsWith('.tmpl')) {
      const content = await fse.readFile(filePath, 'utf-8');
      const processed = processTemplate(content, vars);
      const newPath = filePath.replace(/\.tmpl$/, '');
      await fse.writeFile(newPath, processed);
      await fse.remove(filePath);
    }
  }

  // 5. Write package.json
  await fse.writeFile(join(projectDir, 'package.json'), buildPackageJson(options));

  // 6. Write .env.example
  await fse.writeFile(join(projectDir, '.env.example'), buildEnvExample(options));

  // 7. Write .gitignore
  await fse.writeFile(join(projectDir, '.gitignore'), [
    'node_modules/',
    '.next/',
    '.env',
    '.env.local',
    '.env.*.local',
    '*.tsbuildinfo',
    'next-env.d.ts',
  ].join('\n'));
}

async function listFiles(dir: string): Promise<string[]> {
  const entries = await fse.readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '.git') continue;
      files.push(...await listFiles(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}
